### ISSUE TITLE
password for an encrypted database

### ISSUE THREAD

**Issue by andrewCleverUA** [couchbaselabs/couchbase-lite-java-sqlcipher#8]
In the description it is written:
"The couchbase-lite-java is bundled sqlcipher SQLCipher with libtomcrypt and to provide the database encryption feature."

Please tell me where you have set a password for an encrypted database

**Comment by hideki** [comment]
@pasin, where is this documented?

**Comment by pasin** [comment]
@andrewCleverUA The password will be set from the CBL Android API. In general developers of the Couchbase-Lite-Android will not be interact with the code in this repo directly.

Please note that there will be a several changes regarding to the encryption feature toward 1.2 release. For example we are moving toward to use libcrypto (OpenSSL) instead of libtomcrypt and so on. I would be advice to wait until 1.2 release to use the encryption feature. By that time, all of the related APIs and example codes should be provided.
